### ISSUE TITLE
[Diff from Sisal 3.*] Missing boolean port in reduction nodes

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#10]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer, integer)
    for i in 1,M+N-K
       repeat 
           R1 := i + N;
           R2 := i - K
       returns
           sum of R1; sum of R2
    end for
end function</code></pre>

**Expected result:** 
1) Reduction nodes have boolean port at first position which receives "true" value from constant

**Actual result:**
1) Boolean port is missing in reduction nodes **(image build with SISAL 3.*)**
![Missing_Port_and_Const_Node](https://user-images.githubusercontent.com/6018137/90917835-da83cd00-e40d-11ea-9c14-d34ac067f724.png)

**Comment by parsifal-47** [comment]
Should be resolved with:
https://github.com/parsifal-47/sisal-cl/commit/c5529baf5d65ff6314b87a69372f64fdfbd97d15
