### ISSUE TITLE
[Diff from Sisal 3.*] Multiple "Returns" nodes when loop returns several values

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#11]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer, integer)
    for i in 1,M+N-K
       repeat 
           R1 := i + N;
           R2 := i - K
       returns
           sum of R1; sum of R2
    end for
end function</code></pre>

**Expected result:** 
1) Loop node has single "Returns" node for any number of return values and for any reductions respectively.
**(image build with SISAL 3.*)**
![Expected_Single_Returns_Node](https://user-images.githubusercontent.com/6018137/90919967-9bf01180-e411-11ea-9f76-2c371ea66fca.png)

**Actual result:**
1) Loop node contains multiple "Returns" nodes in case of multiple return values  
**(image build manually for demo purposes)**
![Actual_Multiple_Return_Nodes](https://user-images.githubusercontent.com/6018137/90920728-035a9100-e413-11ea-81ce-793edbfeb1e2.png)

**Comment by parsifal-47** [comment]
should be resolved with:
https://github.com/parsifal-47/sisal-cl/commit/c20054e9263b6651c229ba60eaa2d9ffbc6d9b36
