### ISSUE TITLE
[Diff from Sisal 3.*] Incorrect input ports order in loop return node

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#12]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer, integer)
    for i in 1,M+N-K
       repeat 
           R1 := i + N;
           R2 := i - K
       returns
           sum of R1 * i; sum of R2
    end for
end function</code></pre>

**Expected result:** 
1) "Returns" node receives results of "Body" node. After that index values which can be multiple. And after that arguments of scope function. **(image build with SISAL 3.*)**
![Expected_Ports_Order](https://user-images.githubusercontent.com/6018137/94346779-14717000-0059-11eb-9fae-bf6c9892ef42.png)

**Actual result:**
1) "Returns" node receives results of "Body" node at the end of input ports.
**(image build with Cloud Sisal)**
![Expected_Ports_Order](https://user-images.githubusercontent.com/6018137/94346896-f8220300-0059-11eb-90f8-803ab53a98d1.png)

**Comment by parsifal-47** [comment]
should be resolved with
https://github.com/parsifal-47/sisal-cl/commit/c4d68ea552d153085babca8b3b8d45aebfa1a165
