### ISSUE TITLE
[Diff from Sisal 3.*] Excess "Init" node inside of "Loop" node

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#13]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( N : integer returns integer)
    for i in 1,N
       repeat 
           R := i + N
       returns
           value of R
    end for
end function</code></pre>

**Expected result:** 
1) When initial part of loop expression does not produce an output then there is not "Initial" node inside of "Loop" node. 
**(image build with SISAL 3.*)**
![Expected_Loop_Subnodes](https://user-images.githubusercontent.com/6018137/94347029-19cfba00-005b-11eb-9d4f-30cf3ddf6d44.png)

**Actual result:**
1) There is "Initial" node without output ports.
**(image build with Cloud Sisal)**
![Actual_Loop_Subnodes](https://user-images.githubusercontent.com/6018137/94347100-b3976700-005b-11eb-9171-258fca561438.png)

**Comment by parsifal-47** [comment]
should be resolved with:
https://github.com/parsifal-47/sisal-cl/commit/5828a42a7a1cb57d3d207946764efb2902567f53
