### ISSUE TITLE
[Diff from Sisal 3.*] Two edges to the same port

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#14]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer, integer)
    for i in 1,M+N-K
       repeat 
           R1 := i + N;
           R2 := i - K
       returns
           sum of R1 * i; sum of R2
    end for
end function</code></pre>

**Expected result:** 
1) Reduction receives value to the second port. **(image build with SISAL 3.*)**
![image](https://user-images.githubusercontent.com/6018137/94865400-b46b3700-0467-11eb-81a1-e9b3e767db85.png)

**Actual result:**
1) Two edges to the same port. **(image build with Cloud Sisal)**
![image](https://user-images.githubusercontent.com/6018137/94865433-c2b95300-0467-11eb-92c2-97a6456b8a51.png)

**Comment by parsifal-47** [comment]
sorry, fixed with:
https://github.com/parsifal-47/sisal-cl/commit/609141648f2aec80529a228de4c445df6fbd288f

**Comment by datsis** [comment]
Please take a look at the screen build after fix:
![изображение](https://user-images.githubusercontent.com/6018137/95029193-c3085700-06d0-11eb-86dc-772facd0e877.png)

There is need to redirect edges going to reduction node in order to support backward compatibility to SISAL 3.*.
Also current backend implementation expected that reduction receives guard boolean value into the first port and payload value into the second port.

**Comment by parsifal-47** [comment]
please check now, should be resolved with the latest commit
