### ISSUE TITLE
[Diff from Sisal 3.*] "undefined" in port id of edge

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#15]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer)
    if N = K  then M + N elseif N + 1 > K then M + K else M end if
end function</code></pre>

**Expected result:** 
1) "sourceport" attribute contains correct value, possibly "in0" in this case

**Actual result:**
1) GraphML contains "undefined" in port id (sourceport="**inundefined**"):
```
...
          <edge source="node7" target="node8" sourceport="inundefined" targetport="in0">
            <data key="type">integer</data>
          </edge>
          <edge source="node7" target="node8" sourceport="in1" targetport="in1">
            <data key="type">integer</data>
          </edge>
          <edge source="node8" target="node7" sourceport="out0" targetport="out0">
            <data key="type">boolean</data>
          </edge>
          <edge source="node7" target="node10" sourceport="inundefined" targetport="in0">
            <data key="type">integer</data>
          </edge>
...
```

**Comment by parsifal-47** [comment]
Resolved with:
https://github.com/parsifal-47/sisal-cl/commit/15eea6b7d13319acbb6611067dcf717e7565666b
