### ISSUE TITLE
[Diff from Sisal 3.*] Missing ports and edges when use Let-In expression

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#16]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main(A,B,C: integer returns integer)
    let
        X := A;
        Y := B
    in
        X + Y * C
    end let
end function</code></pre>

**Expected result:** 
1) GraphML shoud be like for Sisal 3.* or there should be enough ports and edges in order to be computable with Let-In node. Please look at IR1 of Sisal 3.*, it does not contain Let-In node at all.
![изображение](https://user-images.githubusercontent.com/6018137/97733515-85012600-1b0a-11eb-93df-a30efb157793.png)

**Actual result:**
1) There are missing edges in GraphML so there is no way to pass values through edges.
   - Let-In node does not have enough input ports
   - There ain't edges passing values from inputs of Main function node to inputs of Let-In node
![изображение](https://user-images.githubusercontent.com/6018137/97733115-fe4c4900-1b09-11eb-888e-8daae2d14231.png)

**Comment by datsis** [comment]
Looks like there are two option at least: 
1. IR should be the same as IR1 for Sisal 3.* (**without** explicit Let-In node) 
2. IR should have enough edges and ports in order to make computation (**with** explicit Let-In node).

Not sure which one would be best for now.
@parsifal-47, what do you think?

**Comment by parsifal-47** [comment]
I'd be happy to keep explicit let-in,
missing edges should be resolved with:
https://github.com/parsifal-47/sisal-cl/commit/f012aecc5bed58cc3b806a8ff419dc9a8d5d2c1e
