### ISSUE TITLE
[Diff from Sisal 3.*] Missing edges from Main function node to If expression node

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#17]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main(X, Y, Z : integer returns integer)
     if X = Y then X
     elseif Y = Z then Z 
     else Y
     end if
end function</code></pre>

**Expected result:** 
1) There are edges from Main function node to If expression node passing function arguments to If node.

**Actual result:**
1) There are missing edges. Please look at picture (build with Sisal3.* just for demo)
![image](https://user-images.githubusercontent.com/6018137/97937440-4c36aa80-1db1-11eb-9822-98cb8fed95e8.png)

**Comment by parsifal-47** [comment]
yes, actually the same with let-in, should be resolved with:
https://github.com/parsifal-47/sisal-cl/commit/f012aecc5bed58cc3b806a8ff419dc9a8d5d2c1e
