### ISSUE TITLE
[Diff from Sisal 3.*] Wrong output ports of loop body node

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#2]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer)
    for i in 1,M
       repeat 
           R := i
       returns
           sum of R
    end for
end function</code></pre>

**Expected result:** 
1) Loop body node should contain single output port since `R := i` denotes only single result of interation

**Actual result:**
<pre><code>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;graphml 
  xmlns="http://graphml.graphdrawing.org/xmlns"
        
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
          http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd"&gt;
  &lt;key id="type" for="node" attr.name="nodetype" attr.type="string" /&gt;
  &lt;key id="location" for="node" attr.name="location" attr.type="string" /&gt;
  &lt;graph id="module" edgedefault="directed"&gt;
    &lt;node id="node1"&gt;
      &lt;data key="type"&gt;Lambda&lt;/data&gt;
      &lt;data key="location"&gt;1:1-8:13&lt;/data&gt;
      &lt;data key="functionName"&gt;Main&lt;/data&gt;
      &lt;port name="in0" type="integer" /&gt;
      &lt;port name="in1" type="integer" /&gt;
      &lt;port name="in2" type="integer" /&gt;
      &lt;port name="out0" type="integer" /&gt;
      &lt;node id="node2"&gt;
        &lt;data key="type"&gt;LoopExpression&lt;/data&gt;
        &lt;data key="location"&gt;2:5-8:1&lt;/data&gt;
        &lt;data key="reduction"&gt;sum&lt;/data&gt;
        &lt;port name="in0" type="integer" /&gt;
        &lt;port name="in1" type="integer" /&gt;
        &lt;port name="in2" type="integer" /&gt;
        &lt;port name="out0" type="integer" /&gt;
        &lt;node id="node3"&gt;
          &lt;data key="type"&gt;Init&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="in0" type="integer" /&gt;
          &lt;port name="in1" type="integer" /&gt;
          &lt;port name="in2" type="integer" /&gt;
          &lt;port name="out0" type="integer" /&gt;
          &lt;port name="out1" type="integer" /&gt;
          &lt;port name="out2" type="integer" /&gt;
        &lt;/node&gt;
        &lt;node id="node7"&gt;
          &lt;data key="type"&gt;Body&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="in0" type="integer" /&gt;
          &lt;port name="in1" type="integer" /&gt;
          &lt;port name="in2" type="integer" /&gt;
          &lt;port name="in3" type="integer" /&gt;
          &lt;port name="out0" type="integer" /&gt;
          <b>&lt;port name="out1" type="integer" /&gt;</b> <b>&lt;--error here</b>
          <b>&lt;port name="out2" type="integer" /&gt;</b> <b>&lt;--error here</b>
          <b>&lt;port name="out3" type="integer" /&gt;</b> <b>&lt;--error here</b>
          <b>&lt;port name="out4" type="integer" /&gt;</b> <b>&lt;--error here</b>
          &lt;edge source="node7" target="node7" sourceport="in3" targetport="out4"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
        &lt;/node&gt;
        &lt;node id="node8"&gt;
          &lt;data key="type"&gt;Returns&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="in0" type="integer" /&gt;
          &lt;port name="in1" type="integer" /&gt;
          &lt;port name="in2" type="integer" /&gt;
          &lt;port name="in3" type="integer" /&gt;
          &lt;port name="in4" type="integer" /&gt;
          &lt;port name="out0" type="integer" /&gt;
          &lt;edge source="node8" target="node8" sourceport="in4" targetport="out0"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
        &lt;/node&gt;
        &lt;node id="node4"&gt;
          &lt;data key="type"&gt;Range&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="in0" type="integer" /&gt;
          &lt;port name="in1" type="integer" /&gt;
          &lt;port name="in2" type="integer" /&gt;
          &lt;port name="out0" type="integer" /&gt;
          &lt;node id="node6"&gt;
            &lt;data key="type"&gt;Literal&lt;/data&gt;
            &lt;data key="location"&gt;2:14-2:15&lt;/data&gt;
            &lt;data key="value"&gt;1&lt;/data&gt;
            &lt;port name="out0" type="integer" /&gt;
          &lt;/node&gt;
          &lt;node id="node5"&gt;
            &lt;data key="type"&gt;Scatter&lt;/data&gt;
            &lt;data key="location"&gt;not applicable&lt;/data&gt;
            &lt;port name="in0" type="integer" /&gt;
            &lt;port name="in1" type="integer" /&gt;
            &lt;port name="out0" type="integer" /&gt;
          &lt;/node&gt;
          &lt;edge source="node6" target="node5" sourceport="out0" targetport="in0"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
          &lt;edge source="node4" target="node5" sourceport="in0" targetport="in1"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
          &lt;edge source="node5" target="node4" sourceport="out0" targetport="out0"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
        &lt;/node&gt;
      &lt;/node&gt;
      &lt;edge source="node1" target="node2" sourceport="in0" targetport="in0"&gt;
        &lt;data key="type"&gt;integer&lt;/data&gt;
      &lt;/edge&gt;
      &lt;edge source="node1" target="node2" sourceport="in1" targetport="in1"&gt;
        &lt;data key="type"&gt;integer&lt;/data&gt;
      &lt;/edge&gt;
      &lt;edge source="node1" target="node2" sourceport="in2" targetport="in2"&gt;
        &lt;data key="type"&gt;integer&lt;/data&gt;
      &lt;/edge&gt;
      &lt;edge source="node2" target="node1" sourceport="out0" targetport="out0"&gt;
        &lt;data key="type"&gt;integer&lt;/data&gt;
      &lt;/edge&gt;
    &lt;/node&gt;
  &lt;/graph&gt;
&lt;/graphml&gt;</code></pre>

**Comment by parsifal-47** [comment]
should be resolved, now body of the given loop has only one output port

```
        <node id="node7">
          <data key="type">Body</data>
          <data key="location">not applicable</data>
          <port name="in0" type="integer" />
          <port name="in1" type="integer" />
          <port name="in2" type="integer" />
          <port name="in3" type="integer" />
          <port name="out0" type="integer" />
          <edge source="node7" target="node7" sourceport="in0" targetport="out0">
            <data key="type">integer</data>
          </edge>
        </node>
```
