### ISSUE TITLE
[Diff from Sisal 3.*] Wrong position of Range node inside of Loop node

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#3]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer)
    for i in 1,M
       repeat 
           R := i
       returns
           sum of R
    end for
end function</code></pre>

**Expected result:** 
1) Range node should be located before Body node like in Sisal 3.*

**Actual result:**
<pre><code>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;graphml 
  &gt;
  ...
  &lt;graph id="module" edgedefault="directed"&gt;
    &lt;node id="node1"&gt;
      ... 
      &lt;node id="node2"&gt;
        ... 
        &lt;node id="node3"&gt;
          ... 
        &lt;/node&gt;
        <b>node 4 expected to be here</b>
        &lt;node id="node7"&gt;
          ...
          &lt;edge &gt;  &lt;/edge&gt;
        &lt;/node&gt;
        &lt;node id="node8"&gt;
          ... 
          &lt;edge &gt;  &lt;/edge&gt;
        &lt;/node&gt;
        <b>&lt;node id="node4"&gt;
          ...
          &lt;node id="node6"&gt;
            ...
          &lt;/node&gt;
          &lt;node id="node5"&gt;
            ...
          &lt;/node&gt;
          &lt;edge ...&gt;  &lt;/edge&gt;
          &lt;edge ...&gt;  &lt;/edge&gt;
          &lt;edge ...&gt;  &lt;/edge&gt;
        &lt;/node&gt;</b>
      &lt;/node&gt;
      &lt;edge &gt; &lt;/edge&gt;
      &lt;edge &gt; &lt;/edge&gt;
      &lt;edge &gt; &lt;/edge&gt;
      &lt;edge &gt; &lt;/edge&gt;
    &lt;/node&gt;
  &lt;/graph&gt;
&lt;/graphml&gt;</code></pre>

**Comment by parsifal-47** [comment]
fixed, now the ordering is:
init, range, precond, body, postcond, reductions
