### ISSUE TITLE
[Diff from Sisal 3.*] Syntax error when loop returns multiple results

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#4]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer, integer)
    for i in 1,M+N-K
       repeat 
           R1 := i + N;
           R2 := i - K
       returns
           sum of R1; sum of R2
    end for
end function</code></pre>

**Expected result:** 
1) successful translation

**Actual result:**
<pre><code>undefined:6844
      throw peg$buildStructuredError(
      ^
peg$SyntaxError: Expected "%", "&", "(", "*", "+", "-", ".", "/", "/=", "<", "<=", "=", ">", ">=", "[", "^", "end", "|", "||", comment, end of line, or whitespace but ";" found.
    at peg$buildStructuredError (eval at compile (...\sisal-cl\node_modules\pegjs\lib\compiler\index.js:67:29), <anonymous>:688:14)
    at Object.peg$parse [as parse] (eval at compile (...\sisal-cl\node_modules\pegjs\lib\compiler\index.js:67:29), <anonymous>:6844:13)
    at Parser.parse (...\sisal-cl\build\parser.js:11:28)
    at Object.<anonymous> (...\sisal-cl\build\sisal.js:18:36)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  message: 'Expected "%", "&", "(", "*", "+", "-", ".", "/", "/=", "<", "<=", "=", ">", ">=", "[", "^", "end", "|", "||", comment, end of line, or whitespace but ";" found.',
  expected: [
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '(', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '.', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '[', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '*', ignoreCase: false },
    { type: 'literal', text: '/', ignoreCase: false },
    { type: 'literal', text: '%', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '+', ignoreCase: false },
    { type: 'literal', text: '-', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '=', ignoreCase: false },
    { type: 'literal', text: '/=', ignoreCase: false },
    { type: 'literal', text: '<', ignoreCase: false },
    { type: 'literal', text: '>', ignoreCase: false },
    { type: 'literal', text: '<=', ignoreCase: false },
    { type: 'literal', text: '>=', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '||', ignoreCase: false },
    { type: 'literal', text: '|', ignoreCase: false },
    { type: 'literal', text: '^', ignoreCase: false },
    { type: 'literal', text: '&', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: 'end', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '(', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '.', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '[', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '*', ignoreCase: false },
    { type: 'literal', text: '/', ignoreCase: false },
    { type: 'literal', text: '%', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '+', ignoreCase: false },
    { type: 'literal', text: '-', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '=', ignoreCase: false },
    { type: 'literal', text: '/=', ignoreCase: false },
    { type: 'literal', text: '<', ignoreCase: false },
    { type: 'literal', text: '>', ignoreCase: false },
    { type: 'literal', text: '<=', ignoreCase: false },
    { type: 'literal', text: '>=', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: '||', ignoreCase: false },
    { type: 'literal', text: '|', ignoreCase: false },
    { type: 'literal', text: '^', ignoreCase: false },
    { type: 'literal', text: '&', ignoreCase: false },
    { type: 'other', description: 'whitespace' },
    { type: 'other', description: 'end of line' },
    { type: 'other', description: 'comment' },
    { type: 'literal', text: 'end', ignoreCase: false }
  ],
  found: ';',
  location: {
    start: { offset: 183, line: 7, column: 21 },
    end: { offset: 184, line: 7, column: 22 }
  },
  name: 'SyntaxError'
}</code></pre>

**Comment by datsis** [comment]
<b>Here goes image of IR produced with Sisal 3.* for given source code where "returns" node contains two "sum" reduction nodes.</b>

![image](https://user-images.githubusercontent.com/6018137/81610290-79f2f600-9403-11ea-964c-eb08eb45dd35.png)

**Comment by parsifal-47** [comment]
list of reductions is added, please check

**Comment by parsifal-47** [comment]
should be resolved
