### ISSUE TITLE
[Diff from Sisal 3.*] Invalid IR xml of "if" expression

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#6]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer)
   if 1 <= 1 then 1
   else 2
   end if   
end function</code></pre>

**Expected result:** 
1) Valid XML of IR

**Actual result:**
1) "<=" substring goes as unescaped so xml is invalid (see below bold text fragment)
<pre><code>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;graphml 
  xmlns="http://graphml.graphdrawing.org/xmlns"
        
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
          http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd"&gt;
  &lt;key id="type" for="node" attr.name="nodetype" attr.type="string" /&gt;
  &lt;key id="location" for="node" attr.name="location" attr.type="string" /&gt;
  &lt;graph id="module" edgedefault="directed"&gt;
    &lt;node id="node1"&gt;
      &lt;data key="type"&gt;Lambda&lt;/data&gt;
      &lt;data key="location"&gt;1:1-5:13&lt;/data&gt;
      &lt;data key="functionName"&gt;Main&lt;/data&gt;
      &lt;port name="in0" type="integer" /&gt;
      &lt;port name="in1" type="integer" /&gt;
      &lt;port name="in2" type="integer" /&gt;
      &lt;port name="out0" type="integer" /&gt;
      &lt;node id="node2"&gt;
        &lt;data key="type"&gt;If&lt;/data&gt;
        &lt;data key="location"&gt;2:4-5:1&lt;/data&gt;
        &lt;port name="out0" type="integer" /&gt;
        &lt;node id="node5"&gt;
          &lt;data key="type"&gt;Condition&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="out0" type="boolean" /&gt;
          &lt;node id="node7"&gt;
            &lt;data key="type"&gt;Literal&lt;/data&gt;
            &lt;data key="location"&gt;2:7-2:8&lt;/data&gt;
            &lt;data key="value"&gt;1&lt;/data&gt;
            &lt;port name="out0" type="integer" /&gt;
          &lt;/node&gt;
          &lt;node id="node8"&gt;
            &lt;data key="type"&gt;Literal&lt;/data&gt;
            &lt;data key="location"&gt;2:12-2:13&lt;/data&gt;
            &lt;data key="value"&gt;1&lt;/data&gt;
            &lt;port name="out0" type="integer" /&gt;
          &lt;/node&gt;
          &lt;node id="node6"&gt;
            &lt;data key="type"&gt;Binary&lt;/data&gt;
            &lt;data key="location"&gt;2:7-2:13&lt;/data&gt;
            &lt;data key="operator"&gt;<h3>&lt;=</h3>
            &lt;/data&gt;
            &lt;port name="in0" type="integer" /&gt;
            &lt;port name="in1" type="integer" /&gt;
            &lt;port name="out0" type="boolean" /&gt;
          &lt;/node&gt;
          &lt;edge source="node7" target="node6" sourceport="out0" targetport="in0"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
          &lt;edge source="node8" target="node6" sourceport="out0" targetport="in1"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
          &lt;edge source="node6" target="node5" sourceport="out0" targetport="out0"&gt;
            &lt;data key="type"&gt;boolean&lt;/data&gt;
          &lt;/edge&gt;
        &lt;/node&gt;
        &lt;node id="node3"&gt;
          &lt;data key="type"&gt;Then&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="out0" type="integer" /&gt;
          &lt;node id="node4"&gt;
            &lt;data key="type"&gt;Literal&lt;/data&gt;
            &lt;data key="location"&gt;2:19-2:20&lt;/data&gt;
            &lt;data key="value"&gt;1&lt;/data&gt;
            &lt;port name="out0" type="integer" /&gt;
          &lt;/node&gt;
          &lt;edge source="node4" target="node3" sourceport="out0" targetport="out0"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
        &lt;/node&gt;
        &lt;node id="node9"&gt;
          &lt;data key="type"&gt;Else&lt;/data&gt;
          &lt;data key="location"&gt;not applicable&lt;/data&gt;
          &lt;port name="out0" type="integer" /&gt;
          &lt;node id="node10"&gt;
            &lt;data key="type"&gt;Literal&lt;/data&gt;
            &lt;data key="location"&gt;3:9-3:10&lt;/data&gt;
            &lt;data key="value"&gt;2&lt;/data&gt;
            &lt;port name="out0" type="integer" /&gt;
          &lt;/node&gt;
          &lt;edge source="node10" target="node9" sourceport="out0" targetport="out0"&gt;
            &lt;data key="type"&gt;integer&lt;/data&gt;
          &lt;/edge&gt;
        &lt;/node&gt;
      &lt;/node&gt;
      &lt;edge source="node2" target="node1" sourceport="out0" targetport="out0"&gt;
        &lt;data key="type"&gt;integer&lt;/data&gt;
      &lt;/edge&gt;
    &lt;/node&gt;
  &lt;/graph&gt;
&lt;/graphml&gt;</code></pre>

**Comment by parsifal-47** [comment]
now < and > are becoming &lt; and &gt; when converting to xml, please check

**Comment by datsis** [comment]
Verified
