### ISSUE TITLE
[Diff from Sisal 3.*] Missing "Range" node inside of "RangeGen" node

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#9]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns integer, integer)
    for i in 1,M+N-K
       repeat 
           R1 := i + N;
           R2 := i - K
       returns
           sum of R1; sum of R2
    end for
end function</code></pre>

**Expected result:** 
1) RangeGen node contains Range node

**Actual result:**
1) Marked RangeGen node is missing inside of Range node **(image build with SISAL 3.*)**
![Missing_Range_Node](https://user-images.githubusercontent.com/6018137/90915601-043af500-e40a-11ea-83b8-08d683ff0818.png)

**Comment by parsifal-47** [comment]
Should be resolved with: https://github.com/parsifal-47/sisal-cl/commit/9d35420910567792e245468c04b5926d46128c8a
